name: Update Substack Feed
on:
  schedule:
    - cron: '0 */3 * * *' # every 3 hours
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch and convert Substack RSS
        run: |
          curl -s "https://gratified.substack.com/feed" > feed.xml
          npx xml2json-cli feed.xml --output feed.json

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.json
          git commit -m "Update Substack feed" || echo "No changes"
          git push
