name: Update Substack Feed

on:
  schedule:
    - cron: '0 * * * *' # runs every hour, adjust if needed
  workflow_dispatch:

jobs:
  fetch-feed:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install xml2js

      - name: Fetch Substack feed
        run: |
          curl -s "https://gratifiedwegrow.substack.com/feed" -o feed.xml

      - name: Convert feed XML to JSON safely
        run: |
          node -e "
          const fs = require('fs');
          const xml2js = require('xml2js');

          const xml = fs.readFileSync('feed.xml', 'utf8');
          xml2js.parseString(xml, { explicitArray: false }, (err, result) => {
            if (err) {
              console.error('XML parse error:', err);
              process.exit(1);
            }
            const items = result.rss.channel.item.map(post => ({
              title: post.title,
              link: post.link,
              date: post.pubDate,
              content: post.description
            }));
            fs.writeFileSync('feed.json', JSON.stringify(items, null, 2));
          });
          "

      - name: Commit updated feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.json
          git commit -m "Update Substack feed" || echo "No changes to commit"
          git push
