name: Update Substack Feed

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Fetch Substack feed
        run: |
          curl -s "https://gratified.substack.com/feed" -o feed.xml

      - name: Convert feed to JSON safely
        run: |
          npm install cheerio
          node -e "
          const fs = require('fs');
          const cheerio = require('cheerio');

          let xml = fs.readFileSync('feed.xml', 'utf8');

          // Quick sanitization of common broken entities
          xml = xml.replace(/&(?!amp;|lt;|gt;|quot;|apos;)/g, '&amp;');

          const $ = cheerio.load(xml, { xmlMode: true });
          const items = [];
          $('item').each((i, el) => {
            items.push({
              title: $(el).find('title').text(),
              link: $(el).find('link').text(),
              date: $(el).find('pubDate').text(),
              content: $(el).find('description').text()
            });
          });

          fs.writeFileSync('feed.json', JSON.stringify(items, null, 2));
          "

      - name: Commit updated feed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add feed.json
          git commit -m "Update feed" || echo "No changes"
          git push
