name: Update Substack Feed

on:
  schedule:
    - cron: '0 * * * *' # runs every hour
  workflow_dispatch:     # allows manual trigger

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install xml2json-cli
        run: npm install -g xml2json-cli

      - name: Fetch Substack RSS feed
        run: curl -s "https://gratified.substack.com/feed" > feed.xml

      - name: Convert RSS XML to JSON
        run: xml2json feed.xml --output feed.json

      - name: Commit updated feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.json
          git diff --quiet && echo "No changes to commit" || git commit -m "Update feed"
          git push
